version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install -r requirements-dev.txt

  pre_build:
    commands:
      - echo "Running tests..."
      - flake8 lambda tests --max-line-length=100 --exclude=__pycache__
      - pytest tests/ -v

  # build:
  #   commands:
  #     - echo "Packaging Lambda..."
  #     - cd lambda/etl_customer
  #     - zip -r function.zip .
  #     - mv function.zip ../../

  build:
  commands:
    - echo "Packaging Lambda..."
    - cd lambda/etl_customer
    - zip -r function.zip .    

artifacts:
  files:
    - lambda/etl_customer/function.zip